name: durability          # 🥉 Bronze durability test-suite

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '**.c'
      - '**.h'
      - 'tests/**'
      - '.github/workflows/durability.yml'
      - 'Makefile'

jobs:
  chaos-suite:
    runs-on: ubuntu-latest     # GitHub’s runner exposes loop + dm
    timeout-minutes: 15

    steps:
      - name: ⬇️  Checkout
        uses: actions/checkout@v4

      - name: 🛠 Install build & chaos deps
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y build-essential curl \
                                   libuv1-dev dmsetup \
                                   losetup util-linux   # mkfs.ext4 \
                                   zlib1g-dev libhttp-parser-dev
      - name: ⚙️  Build RamForge
        run: make          # expects default target to produce ./ramforge

      - name: ✅ Unit tests (CRC + multi-fork)
        run: make test

      - name: 🧨 Chaos tests (hard-kill • disk-full • power-loss)
        run: |
          sudo -E env "PATH=$PATH" make chaos

      - name: 📂 Archive chaos logs if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: chaos-logs
          path: |
            ./tests/chaos/*.log
            ./append.aof
            ./dump.rdb
          if-no-files-found: ignore
